
//入口模块
let app=angular.module("app",["ui.router","appController"]);
//定义一个type表示是学生还是老师
app.config(["$stateProvider",function($stateProvider){
    //$urlRouteProvider("/index");
    $stateProvider.state("index",{
        url:"/index",
        templateUrl:"views/main_index.html",
        controller:"IndexController"
        }
    ).state("index.show",{
        url:"/show",
        templateUrl:"views/main_index_show.html",
        controller:"IndexController"
        }
    ).state("index.show.update",{
        url:"/update",
        templateUrl:"views/index_show_update.html",
        controller:"IndexController"
        }
    ).state("set_password",{
        url:"/set_password",
        templateUrl:"views/set_passwod.html",
        controller:"loginController"
        }
    ).state("major",{
        url:"/major",
        templateUrl:"views/major.html",
        controller:"majorController"
        //老师专业管理界面的专业查询结果
    }).state("major.search",{
        url:"/search",
        templateUrl:"views/major_search.html",
        controller:"major_searchController"
        //学生专业管理界面的专业查询
    }).state("major.student_search",{
        url:"/student_search",
        templateUrl:"views/major_student_search.html",
        controller:"major_searchController",
         //学生专业管理界面的专业查询结果
    }).state("major.student_search.show",{
        url:"/show",
        templateUrl:"views/major_student_search_show.html",
        controller:"major_searchController",
        //学生本专业的专业信息
    }).state("major.current",{
        url:"/current",
        templateUrl:"views/major_current.html",
        controller:"major_currentController",
    }).state("courses",{
        url:"/courses",
        templateUrl:"views/courses.html",
        controller:"coursesController"
        //本学期课程
    }).state("courses.current",{
        url:"/current",
        templateUrl:"views/courses_current.html",
        controller:"coursesController",
        //课程查询，不需要控制器，输入信息的获取由courses_search_showController双向绑定
    }).state("courses.search",{
        url:"/search",
        templateUrl:"views/courses_search.html",
    }).state("courses.search.show",{
        url:"/show",
        templateUrl:"views/courses_search_show.html",
        controller:"courses_search_showController",
        //学生选课控制器
    }).state("courses.select",{
        url:"/select",
        templateUrl:"views/courses_select.html",
        controller:"courses_selectController",
    }).state("score",{
        url:"/score",
        templateUrl:"views/score.html",
        controller:"score_inputController"
        //成绩录入
    }).state("score.input",{
        url:"/input",
        templateUrl:"views/score_input.html",
        controller:"score_inputController",
        //老师成绩修改
    }).state("score.search",{
        url:"/search",
        templateUrl:"views/score_search.html",
        controller:"score_search_showController",
        //老师成绩查询结果
    }).state("score.search.show",{
        url:"/show",
        templateUrl:"views/score_search_show.html",
        controller:"score_search_showController",
        //显示学生全部成绩
    }).state("score.all",{
        url:"/all",
        templateUrl:"views/score_all.html",
        controller:"scoreController",
        //显示学生不及格成绩
    }).state("score.bad",{
        url:"/bad",
        templateUrl:"views/score_bad.html",
        controller:"scoreController",
        //显示老师本学期成绩
    }).state("score.current",{
        url:"/current",
        templateUrl:"views/score_current.html",
        controller:"scoreController",
    }).state("information",{
        url:"/information",
        templateUrl:"views/selfInformation.html",
        controller:"infController"
        //老师成绩录入
    }).state("score.input.show",{
        url:"/show",
        templateUrl:"views/score_input_show.html",
        controller:"score_inputController"
        //老师成绩修改
    }).state("score.input.update",{
        url:"/update",
        templateUrl:"views/score_update_show.html",
        controller:"score_inputController"

    })
}]);



